default: &default
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

test:
  access_key_id:
  secret_access_key:

development:
  <<: *default

production:
  <<: *default
