default: &default
  adapter: postgresql
  encoding: unicode
  database: cybfootball

development:
  <<: *default

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  pool: 5

production:
  <<: *default
  password: <%= ENV['CYBFOOTBALL_DATABASE_PASSWORD'] %>
