default: &default
  adapter: postgresql
  encoding: unicode
  database: cybfootball

development:
  <<: *default

test:
  <<: *default
  database: cybfootball_test

production:
  <<: *default
  password: <%= ENV['CYBFOOTBALL_DATABASE_PASSWORD'] %>
