default: &default
  adapter: mysql2
  encoding: utf8
  database: my_db_name

development:
  <<: *default
  database: cybfootball
  username: root
  host: 127.0.0.1
  port: 3306

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  pool: 5

production:
  <<: *default
  password: <%= ENV['DB_PASSWORD'] %>
